// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mowmyemymytbjfirhlhh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1vd215ZW15bXl0YmpmaXJobGhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxOTc4MjUsImV4cCI6MjA2Mzc3MzgyNX0.0UZbgc8FNc9B5xUu8uEcj88PDNEPFkBhAV4NlCMtyKI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);